data:
  dataset: "Chengdu"
  miss_mechanism: "MCAR"
  miss_ratio: 0.5
  batch_size: 16
  test_batch_size: 16
  val_batch_size: 16

model:
  num_nodes: 524
  hidden_size: 16
  in_channel: 1
  seqlen: 6
  st_block: 3
  K: 4
  d_model: 512
  n_heads: 4

train:
  cuda: 0
  lr: 1e-3
  epochs: 150
  save_model_path: save_model/
  result_path: results/
